version: '3.8'  # Версия формата файла, стандартная

services:       # Здесь мы перечисляем, какие "капсулы" нам нужны
  db:           # Название сервиса (придумали сами, пусть будет db)
    image: postgres:15  # Какой чертеж брать. Postgres 15-й версии
    container_name: my_postgres_db  # Как контейнер будет называться в Docker Desktop
    environment:        # Переменные окружения (настройки внутри капсулы)
      POSTGRES_USER: admin      # Логин администратора
      POSTGRES_PASSWORD: root   # Пароль (для локалки сойдет простой)
      POSTGRES_DB: analytics_db # Имя базы данных, которая создастся сразу
    ports:
      - "5432:5432"     # Самое важное! <порт на твоем компе>:<порт внутри капсулы>
                        # Теперь, стучась на localhost:5432, ты попадешь в базу
    volumes:
      - ./pg_data:/var/lib/postgresql/data # Чтобы данные не исчезли после выключения!
                        # Мы говорим: "Сохраняй всё, что в базе, в папку pg_data у меня в проекте"
